name: docker
on:
  push:
    branches:
      - master
      - build-* # to build without PR
    tags:
      - v*
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "30 15 * * *" # 7:30 PST (-8), 8:30 PDT (-7)

env:
  OSXCROSS_REVISION: 4287300a5c96397a2ee9ab3942e66578a1982031
  XCODE_VERSION: '12.4'
  MACOS_SDK_VERSION: '11.1'

jobs:
  macos-sdk:
    name: Package MacOSX SDK
    runs-on: macos-latest
    steps:
      - uses: actions/cache@v2
        id: macos-sdk-cache
        with:
          key: macos-sdk-${{ env.OSXCROSS_REVISION }}-${{ env.XCODE_VERSION }}-v1
          path: osxcross/tarballs/MacOSX${{ env.MACOS_SDK_VERSION }}.sdk.tar.xz
      - name: Package MacOSX SDK
        if: steps.macos-sdk-cache.outputs.cache-hit != 'true'
        run: |
          curl -sSLf https://github.com/tpoechtrager/osxcross/archive/${OSXCROSS_REVISION}.tar.gz | tar zxf -
          mv osxcross-${OSXCROSS_REVISION} osxcross
          pushd osxcross
          XCODEDIR=/Applications/Xcode_${XCODE_VERSION}.app tools/gen_sdk_package.sh
          mv MacOSX${MACOS_SDK_VERSION}.sdk.tar.xz tarballs/
          popd

  osxcross:
    name: Build osxcross
    runs-on: ubuntu-latest
    needs:
      - macos-sdk
    steps:
      - name: Download osxcross
        run: |
          curl -sSLf https://github.com/tpoechtrager/osxcross/archive/${OSXCROSS_REVISION}.tar.gz | tar zxf -
          mv osxcross-${OSXCROSS_REVISION} osxcross
      - uses: actions/cache@v2
        with:
          key: macos-sdk-${{ env.OSXCROSS_REVISION }}-${{ env.XCODE_VERSION }}-v1
          path: osxcross/tarballs/MacOSX${{ env.MACOS_SDK_VERSION }}.sdk.tar.xz
      - uses: actions/cache@v2
        id: osxcross-cache
        with:
          key: osxcross-${{ runner.os }}-${{ env.OSXCROSS_REVISION }}-${{ env.XCODE_VERSION }}-v1
          path: osxcross/target
      - name: Build osxcross
        if: steps.osxcross-cache.outputs.cache-hit != 'true'
        run: |
          pushd osxcross
          sudo tools/get_dependencies.sh
          UNATTENDED=1 ./build.sh
          popd

  build-aarch64-darwin:
    name: Build mitamae-aarch64-darwin with osxcross
    runs-on: ubuntu-latest
    needs:
      - osxcross
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          # Ruby >= 3.0 isn't usable now because Rakefile in mruby v2.0.1 has kwargs problem.
          # https://github.com/mruby/mruby/blob/2.0.1/Rakefile#L37
          ruby-version: '2.7'
          bundler-cache: true
      - uses: actions/cache@v2
        id: osxcross-cache
        with:
          key: osxcross-${{ runner.os }}-${{ env.OSXCROSS_REVISION }}-${{ env.XCODE_VERSION }}-v1
          path: osxcross/target
      - name: Build mitamae
        run: |
          export PATH="$PWD/osxcross/target/bin:$PATH"
          bundle exec rake compile BUILD_TARGET=darwin-aarch64
          mkdir -p mitamae-build
          cp mruby/build/darwin-aarch64/bin/mitamae mitamae-build/mitamae-aarch64-darwin
          pushd mitamae-build
          tar zcvf mitamae-aarch64-darwin.tar.gz mitamae-aarch64-darwin
          popd
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: mitamae-aarch64-darwin
          path: mitamae-build/
